itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[3]/div/div[1]/h1/span[2]
itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[1]/h1/span
price =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[2]/div[1]/div/div[1]
price =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[3]/div[1]/div/div[1]
price =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[3]/div/div[2]/div[1]/div/div[1]
price =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[3]/div/div[3]/div[1]/div/div[1]
price =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[4]/div[1]/div/div[1]
discount =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/span
discount =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[3]/div[1]/div/div[3]/span
discount =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[3]/div/div[2]/div[1]/div/div[3]/span
discount =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[3]/div/div[3]/div[1]/div/div[3]/span
discount =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div/div[4]/div[1]/div/div[3]/span
c1 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div[1]/div/div[2]/a
c1 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[7]/div/div/p
c2 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div[1]/div/div[3]/a
c2 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[7]/div/div/p
c3 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div[1]/div/div[4]/a
c3 =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[7]/div/div/p
photo =   //*[@id="container"]/div/div[3]/div[1]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div/img')).getAttribute("src");
photo =   //*[@id="container"]/div/div[3]/div[1]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div[2]/img')).getAttribute("src");
itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div/div/div[1]/div[5]/a
itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div/div/div[1]/div[4]/a
itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div/div/div[1]/div[3]/a
itemText =   //*[@id="container"]/div/div[3]/div[1]/div[2]/div[1]/div/div/div[1]/div[2]/a
itemText =   //*[@id="container"]/div/div[3]/div/div[2]/div[1]/div/div/div[1]/div[6]/a
itemText =   //*[@id="container"]/div/div[3]/div/div[2]/div[1]/div/div/div[1]/div[5]/a
itemText =   //*[@id="container"]/div/div[3]/div/div[2]/div[1]/div/div/div[1]/div[4]/a
itemText =   //*[@id="container"]/div/div[3]/div/div[2]/div[1]/div/div/div[1]/div[3]/a
itemText =   //*[@id="container"]/div/div[3]/div/div[2]/div[1]/div/div/div[1]/div[2]/a